"""add nullable property to user attributes 

Revision ID: 25848b97b1ca
Revises: 576167db48c2
Create Date: 2019-09-14 18:59:42.477080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25848b97b1ca'
down_revision = '576167db48c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('secure_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
